apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backend
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
images:
- name: backend
  newName: docker.io/kuzmenkoserhii053/finaldan-backend
  digest: sha256:a4287c8ccfda4df0ee4c700d6dc19fb406761d59176331866ddfddcbbca79904
