apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backend
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
images:
- name: backend
  newName: docker.io/kuzmenkoserhii053/finaldan-backend
  digest: sha256:cc90f6502a3d05b6bc51ea314135f26b934ebfa0a48ed8bb42aa1874e04d712f
